-- set custom highlights here

local bg = "#000000"
local alt_bg = "#0f0f0f"

vim.cmd.highlight("BlinkCmpDoc guibg=" .. bg)
vim.cmd.highlight("BlinkCmpDocBorder guibg=" .. bg)
vim.cmd.highlight("BlinkCmpMenu guibg=" .. bg)
vim.cmd.highlight("BlinkCmpMenuBorder guibg=" .. bg)
vim.cmd.highlight("BlinkCmpMenuSelection guibg=" .. alt_bg)
vim.cmd.highlight("BlinkCmpSignatureHelp guibg=" .. bg)
vim.cmd.highlight("BlinkCmpSignatureHelpBorder guibg=" .. bg)
vim.cmd.highlight("CursorLine guibg=" .. alt_bg)
vim.cmd.highlight("FloatBorder guibg=" .. bg)
vim.cmd.highlight("Normal guibg=" .. bg)
vim.cmd.highlight("NormalFloat guibg=" .. bg)
vim.cmd.highlight("NormalNC guibg=" .. bg)
vim.cmd.highlight("NormalSB guibg=" .. bg)
vim.cmd.highlight("Pmenu guibg=" .. bg)
vim.cmd.highlight("SnacksNotifierBorderDebug guibg=" .. bg)
vim.cmd.highlight("SnacksNotifierBorderError guibg=" .. bg)
vim.cmd.highlight("SnacksNotifierBorderInfo guibg=" .. bg)
vim.cmd.highlight("SnacksNotifierBorderWarn guibg=" .. bg)
vim.cmd.highlight("SnacksNotifierDebug guibg=" .. bg)
vim.cmd.highlight("SnacksNotifierError guibg=" .. bg)
vim.cmd.highlight("SnacksNotifierInfo guibg=" .. bg)
vim.cmd.highlight("SnacksNotifierTrace guibg=" .. bg)
vim.cmd.highlight("SnacksNotifierWarn guibg=" .. bg)
vim.cmd.highlight("SnacksPickerInputBorder guibg=" .. bg)
vim.cmd.highlight("SnacksPickerListCursorLine guibg=" .. alt_bg)
vim.cmd.highlight("SnacksPickerPreviewCursorLine guibg=" .. alt_bg)
vim.cmd.highlight("TreesitterContext guibg=" .. alt_bg)
vim.cmd.highlight("TreesitterContextLineNumber guifg=orange gui=bold")
vim.cmd.highlight("statusline guibg=" .. bg)
